@url = http://localhost
@port = 3000
###
GET {{url}}:{{port}}/users
###
POST {{url}}:{{port}}/posts
Content-Type: application/json

{
    "title" :   "test the json mock server",
    "author" : "tester 3"
}
###